### ISSUE TITLE
css-variables theme

### ISSUE THREAD

**Issue by johnhooks** [KevinBatdorf/code-block-pro#131]
I don't see a way to use the `css-variables` Shiki theme. I'd like to use it so I can alternate between a light and dark mode. Thanks for this project it works really well. Also FYI, if the `css-variables` theme was part of the premium package I would definitely buy it!

**Comment by KevinBatdorf** [comment]
I think shiki doesn't actually build it and that theme is just lingering there in the build for some reason. I'll report it upstream and see if they want to fix it. If they do I'll include it free. If I need to add manually it I'll have to add it to the add-on themes. Happy to do either though.

Can you link to the theme on the vs code marketplace? I'll have to find the grammar file

**Comment by KevinBatdorf** [comment]
You know what. I completely misunderstood what that theme was doing. Hmm I'll have to think about how to handle that. That might be something I add to the premium version simply because adding a UI to the free version would completely nullify the premium one 😅

I'll look for a solution when I can. That's actually pretty neat.

**Comment by johnhooks** [comment]
Awesome @KevinBatdorf I appreciate you looking into it. It's a really cool theme that allows for dynamically changing the highlighting on the fly. I built a highlighter that used it for a SvelteKit project, but then decided I shouldn't rebuild a CMS to blog... I should just use WordPress 🤦.

**Comment by KevinBatdorf** [comment]
Haha right. You could also use WP headless with svelte with WP as the data source only. The code block would work in that case too with no frontend JS (minus a few features like copy button - but you could add the JS manually too)

I think I could add a UI for light/dark mode as well and let you assign the colors in the editor directly. I'll have to plan this a bit so the user can do it both per block and have a global override somehow.

**Comment by johnhooks** [comment]
@KevinBatdorf I would be happy with either option.

Totally off topic, I am just jumping into WP world from a TypeScript heavy background, it's been a bit jarring. Though finding your plugins has given me some good repos to study how to use modern JS/TS in WP Blocks. Thanks!

**Comment by KevinBatdorf** [comment]
Oh nice! Yeah WordPress development in general has mostly been done in PHP even but the last few years with [Gutenberg](https://github.com/WordPress/gutenberg) WordPress is becoming a React app over time. 

Gutenberg is starting to slowly convert the code to TypeScript as well so I think that will start to influence more WordPress developers to embrace TypeScript. So if you end up enjoying working with WordPress then now is the best time to get started since you're ahead of that trend.

**Comment by KevinBatdorf** [comment]
I'm still going to work on this, but need another week or two. I was away for 5 weeks so didn't have a ton of free time. Another temporary option, you could edit the `defaultThemes.json` and add `css-variables` actually, but you would have to always keep it updated if I make a release

**Comment by johnhooks** [comment]
No rush, my code syntax can be highlighted in a predefined. I was just sharing that the css-variable theme was cool and would be a good addition.

**Comment by KevinBatdorf** [comment]
This was added to the pro version now in a somewhat manual way. I'll likely add some UI to manage custom themes when I get around to it.

https://github.com/KevinBatdorf/code-block-pro/discussions/168
