### ISSUE TITLE
Wishlist: bash & filenames

### ISSUE THREAD

**Issue by antrys** [KevinBatdorf/code-block-pro#133]
Love the plugin.
I wish is supported bash scripting.
I've been setting it to javascript or php and it's close enough, I guess.
Normally, I've been having to use HCB for bash script examples have been using this for terminal output examples. But the look isn't consistent.

As an aside, maybe it's available but I can't find it; Being able to put a filename into the header, would be super-handy.

Thanks again for a great plugin!

**Comment by KevinBatdorf** [comment]
You can use `shellscript`. I'll add bashas an alias for it in the next release. Good call. 

You can select a custom header, then in the settings panel you can change the text to whatever you'd like. I'll update this too to have that field closer to the header settings too in (maybe) the next update. I can see how that's not super clear. 

BTW if you have terminal output you can try the `ANSI` language option. It's a bit WIP though so might be buggy in some cases, like when you have bg colors. For example:

![216741118-e174b747-a934-4eac-b4ad-648ce60c7560](https://user-images.githubusercontent.com/1478421/219923210-e7b94ff4-e26a-4a28-89af-eec1940b7ca0.png)


Thanks for the feedback. How are you liking the plugin otherwise? Any missing features you expect?

**Comment by antrys** [comment]
Holy Smokes, it just went from being OK, to being the best thing since sliced bread!
Your explanations just solved a ton of problems I was having with look and feel of my pages.
This plugin is now my go-to!

As far as features, it's more of a UI thing: 
I bounce around, a lot, between Gutenberg blocks while I'm writing and still figuring out the look and feel for the post. 
I noticed that if I'm trying to match the style of several blocks, when I go to a block to see what it has as it's theme, the active theme doesn't seem to be indicated in any way, over on the right, and I have to go through the whole list one-by-one to figure out which one it is (well, now it's "had" because I changed it by searching.)  Also, the header isn't shown in the theme previews so I don't know what colors FG/BG will be until I change it. 

But seriously, with your help above, you just took me to the next-level.  Big Thanks!

**Comment by KevinBatdorf** [comment]
Nice! The header not showing must be some sort of bug. Car to share a screenshot? 

> when I go to a block to see what it has as it's theme

Yeah that is a bit annoying. I opened an issue on that [here](https://github.com/KevinBatdorf/code-block-pro/issues/130) and will probably add it to the toolbar for the next release.

**Comment by antrys** [comment]
Here ya go. (I'm on Brave on Linux)
![Screenshot_20230219_032431](https://user-images.githubusercontent.com/13042832/219937270-d933f5cd-ab06-4bf1-b45b-82ed121eb3c1.png)

**Comment by KevinBatdorf** [comment]
Oh right. I misread your previous message. That's intentional but I get your point. Maybe I can add a setting to toggle headers/footers in the preview.
