### ISSUE TITLE
Error in highlighting a text

### ISSUE THREAD

**Issue by irsdl** [KevinBatdorf/code-block-pro#226]
Creating a highlight snippet using the following code causes an error when re-opening the post in the editor:

```
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
```

![image](https://github.com/KevinBatdorf/code-block-pro/assets/1798313/874bdb4d-6637-40f1-8cd0-cd10c25fe061)

Save and re-opening it will show this:
![image](https://github.com/KevinBatdorf/code-block-pro/assets/1798313/d13102a7-6bb8-4228-8b4b-730748ae3bca)

**Comment by KevinBatdorf** [comment]
Interesting. I just test it and it seems any string ending with `\` crashes it. I'll investigate later. Thank you again for writing this up.

**Comment by KevinBatdorf** [comment]
This is sort of "fixed" now in that you can go under "Extra Settings" and select "Encode special characters". It will encode it a bit differently with that option enabled, and this character sequence should work. The issue is the WP parser is crashing if there's a `\`. 

If it's still not working for you though, let me know. You may need to re-add it though
